version: '2'

services:
   nginx:
      build:
         context: ./
         dockerfile: Dockerfile.nginx
      env_file:
        - ./env.local
      ports:
         - 443:443
      volumes:
         # IMPORTANT: do not use these snake-oil certs in production!
         - ./cert:/etc/ssl/nginx

   webapp:
      build:
         context: ./
         dockerfile: Dockerfile
      ports:
         - 9090
      env_file:
         - ./env.local
      volumes:
         - $HOME/botanist/repos:/botanist/repos

   ldap:
      image: osixia/openldap
      ports:
         - 389:389
      environment:
         - LDAP_DOMAIN=example.com
         - LDAP_ORGANISATION="Example Ltd."

   # this runs to add a test user to the ldap docker container and then exits
   # you can log in with username: test and password: t3st
   ldapinit:
      build:
         context: ./
         dockerfile: Dockerfile.ldapinit
      depends_on:
         - ldap
      command: dockerize -wait tcp://ldap:389 ldapadd -v -h ldap -c -x -D cn=admin,dc=example,dc=com -w admin -f /tmp/sample.ldif
